### ISSUE TITLE
Toggle command

### ISSUE THREAD

**Issue by ilAYAli** [neoclide/coc-git#10]
Is it possible to toggle the gutter as with  `:GitGutterTooggle`?

**Comment by ilAYAli** [comment]
I assume that I have to  do something like`:CocUpdate` to get the latest version of the extension, and then`:CocCommand git.toggleGutters`?


It is not obvious from the commit what I need to do, and the steps above does not work.
I guess that the extension isn't updated to HEAD as the command is not shown in `:CocList commands`?

**Comment by chemzqm** [comment]
Not published yet, need use vim-plug and build the javascript yourself to get it work.
