### ISSUE TITLE
"you" in blames

### ISSUE THREAD

**Issue by vegerot** [neoclide/coc-git#102]
Would it be possible for the inline blame feature to parse my gitconfig, figure who "I" am, and in the blames say "you" instead of my full name?

**Comment by chemzqm** [comment]
I don't think it makes too much sense, since the git user name could be changed.

**Comment by vegerot** [comment]
Isn't this also a potential problem in every other editor too?
btw I was also wondering (maybe I should make a separate issue for this) if I could disable the text "Not Committed Yet" and just have nothing there instead.  Again, this is like many other editors

**Comment by vegerot** [comment]
On closer, what is happening [here](https://github.com/neoclide/coc-git/blob/master/src/manager.ts#L727)?  It looks like it is trying to say "You", but in my editor it just says my full name

edit: and looking at the compiled javascript, I just have 
<img width="670" alt="image" src="https://user-images.githubusercontent.com/5297725/79795963-c1192a00-8322-11ea-8da2-f277a02c33af.png">

**Comment by vegerot** [comment]
final edit

Ah, @chemzqm you [cheeky](https://github.com/neoclide/coc-git/blame/623a5351c8eca639e3cffee38f941426f2df2422/src/manager.ts#L727) developer you.  Say you're not gonna do it but then surprise me with it anyways!  Thank you so much, man

last final edit: about how often do you update the npm releases on average?

**Comment by chemzqm** [comment]
Don't know, should be quite often.

**Comment by vegerot** [comment]
@chemzqm thanks.  It's nbd since I just built it myself, but I asked so I'd know when to start tracking npm again

P.S. if you are really worried about people changing their names you could make the "you" go by email instead of name.  I don't know if there's ever a bunch of "John Smith"s working on the same codebase lol.  I think doing it off of the name though is good, because that's extremely unlikely, but the email is guaranteed to be unique.  Thank you again! 😊 🙏
