### ISSUE TITLE
Can not work properly with symbolic files

### ISSUE THREAD

**Issue by gongxiao** [neoclide/coc-git#103]
open a symbolic file in non-git folder.
the source of symbolic file is in git repository.
git.chunkInfo works good, but git.chunkStage and git.chunkUndo well not work.

## versions

vim version: NVIM v0.4.3
node version: v12.14.1
coc.nvim version: 0.0.77-817efd5108
term: xterm-256color
platform: linux

## Output channel: git

Looking for git in: git
> git rev-parse --show-toplevel
resolved root: /home/XXX
> git ls-files -- config/.vimrc
resolved root: /home/XXX
> git symbolic-ref --short HEAD
> git --no-pager show :config/.vimrc
> git diff --name-status
> git diff --staged --name-status
> git ls-files --others --exclude-standard
resolved root: /home/XXX
> git ls-files -- config/.vimrc
> git --no-pager show :config/.vimrc
> git diff /home/XXX/config/.vimrc
resolved root: /home/XXX
resolved root: /home/XXX
> git symbolic-ref --short HEAD
> git ls-files -- config/.vimrc
> git diff --name-status
> git diff --staged --name-status
> git ls-files --others --exclude-standard
> git --no-pager show :config/.vimrc
> git diff /home/XXX/config/.vimrc
resolved root: /home/XXX
resolved root: /home/XXX
> git symbolic-ref --short HEAD
> git ls-files -- config/.vimrc
> git diff --name-status
> git diff --staged --name-status
> git ls-files --others --exclude-standard
> git --no-pager show :config/.vimrc
> git diff /home/XXX/config/.vimrc
resolved root: /home/XXX
resolved root: /home/XXX
> git symbolic-ref --short HEAD
> git ls-files -- config/.vimrc
> git diff --name-status
> git diff --staged --name-status
> git ls-files --others --exclude-standard
> git --no-pager show :config/.vimrc
> git diff /home/XXX/config/.vimrc
> git apply --cached --unidiff-zero -
error: ../.vimrc: does not exist in index

Error 1 on: 'git apply --cached --unidiff-zero -' in /home/XXX
error: ../.vimrc: does not exist in index
resolved root: /home/XXX
resolved root: /home/XXX
> git symbolic-ref --short HEAD
> git ls-files -- config/.vimrc
> git diff --name-status
> git diff --staged --name-status
> git ls-files --others --exclude-standard
> git --no-pager show :config/.vimrc
> git diff /home/XXX/config/.vimrc

**Comment by chemzqm** [comment]
Fixed by 44251bf
