### ISSUE TITLE
Fugitive's Gstatus not updating on :CocCommand git.chunkStage or :CocCommand git.chunkUndo

### ISSUE THREAD

**Issue by jmolero** [neoclide/coc-git#104]
I use this command with a map like this:

```
nmap <silent><leader>hs :CocCommand git.chunkStage<CR>
```

As a workaround I added a write at the end to update the Gstatus window:

```
nmap <silent><leader>hs :CocCommand git.chunkStage<CR>:w<CR>
```

Would it be possible to update Gstatus from coc-git when staging or undoing a chunk?

Thank you!

**Comment by chemzqm** [comment]
Looks like you have to save your code

**Comment by jmolero** [comment]
Ok, thanks!
