### ISSUE TITLE
How do I create key mappings for other commands?

### ISSUE THREAD

**Issue by kuntau** [neoclide/coc-git#112]
Sometimes I prefer key mappings than CocCommands but I tried
```viml
nmap <leader>gs <Plug>(coc-git-chunkstage)
nmap <leader>gu <Plug>(coc-git-chunkundo)
```
but it didn't work.

**Comment by chemzqm** [comment]
Map to CocCommand

**Comment by kuntau** [comment]
Hi. I know the CocCommand just asking for the consistency why some command have <plug> version while others don't. I poke around in the source but can't find where this command was created.

Thank you any way :beers:

**Comment by chemzqm** [comment]
No key-mapping for it since I don't think it's frequently used.
