### ISSUE TITLE
Hide remote branches

### ISSUE THREAD

**Issue by itainoam** [neoclide/coc-git#117]
Thanks for the useful plugin!

Is it possible to not show remote branches by default?  
https://github.com/neoclide/coc-git/blob/52100ea6b847ddbd3961990bb68f9e8482656478/src/lists/branches.ts#L74

Most times I'd like to checkout local branches, and it'd be nice if `-a` could be passed as an optional argument.

Also a bit unrelated, I'm sorting the branches by date:
`"list.source.branches.defaultArgs": ["--sort", "-committerdate"]`
After I start typing the order is not kept. Is there anything to do about this?

**Comment by itainoam** [comment]
Why was this closed?

**Comment by chemzqm** [comment]
It fixed, `-a` is removed and I can't reproduce the sort issue.

**Comment by itainoam** [comment]
Thanks I can confirm the first issue was solved!!

Here's a gif of the sorting issue if that help:
![bug](https://user-images.githubusercontent.com/12605830/84490796-5940e900-acac-11ea-881b-0db36202ebd0.gif)
