### ISSUE TITLE
coc-git is too colorful which can attract developer's attention from code...

### ISSUE THREAD

**Issue by 0x8f701** [neoclide/coc-git#119]
![image](https://user-images.githubusercontent.com/33961674/85408640-12cd7300-b565-11ea-8818-7321fa4917d8.png)

Hi, recently I switched from `ycm` to coc.nvim, I also stopped using `vim-gigutter` similar plugins and switch to `coc-git`.

I haven't tested all the features yet but just found it's too colorful.I think the default config may need to changed.

**Comment by chemzqm** [comment]
Try minimal vimrc.
