### ISSUE TITLE
[Feature requests] Allow to jump into the chunkInfo window 

### ISSUE THREAD

**Issue by voldikss** [neoclide/coc-git#12]
`:CocCommand git.chunkInfo` 可以打开下面 diff 窗口，能不能增加一个让光标进入这个窗口的功能？
![2019-05-22 16-35-39 的屏幕截图](https://user-images.githubusercontent.com/20282795/58159725-b2a83580-7caf-11e9-8f3b-67dfb97bafb7.png)

比如，在 diff 窗口已经存在的情况下，再次执行`:CocCommand git.chunkInfo`则使光标进入窗口之类的。

related issue: https://github.com/iamcco/git-p.nvim/issues/5

**Comment by chemzqm** [comment]
用 `<C-w>p` 就可以了。
