### ISSUE TITLE
Git blame info is not showing if text changed

### ISSUE THREAD

**Issue by rjshrjndrn** [neoclide/coc-git#121]
If I update some text, till I write those changes to disk, blame info is not showing up
![coc-git](https://user-images.githubusercontent.com/2563385/86539885-cba89000-bf1d-11ea-8f6c-61b88b08aff1.gif)

**Comment by chemzqm** [comment]
It's expected.

**Comment by CallumHoward** [comment]
https://github.com/APZelos/blamer.nvim is able to handle this case

==EDIT==
I take it back, blamer.nvim shows outdated blame (technically inaccurate) until you save.

**Comment by chemzqm** [comment]
I've made git blame to invoke with current buffer content.

**Comment by rjshrjndrn** [comment]
Woohoo... Thank you @chemzqm
