### ISSUE TITLE
How to integrate with vim-airline?

### ISSUE THREAD

**Issue by yuriusu22** [neoclide/coc-git#122]
Hi, I just want the git branch status with auto update to be shown in my status line. I'm using the [vim-airline](https://github.com/vim-airline/vim-airline) plugin:

![vim-airline-demo](https://github.com/vim-airline/vim-airline/wiki/screenshots/demo.gif)

How do I properly configure it?

**Comment by chemzqm** [comment]
Please read it's document.

**Comment by yuriusu22** [comment]
@chemzqm My bad, I didn't include more info regarding the issue. But here's what I came up with:

```
function! s:update_git_status()
  let g:airline_section_b = "%{get(g:,'coc_git_status','')}"
endfunction

let g:airline_section_b = "%{get(g:,'coc_git_status','')}"

autocmd User CocGitStatusChange call s:update_git_status()
```

And here's what it looks like:

![Screenshot_20200707-132456_Termux](https://user-images.githubusercontent.com/66087162/86718075-550eae00-c055-11ea-9677-2d11fea9dbb1.png)

How can I fix the `...` in the git branch name?

**Comment by chemzqm** [comment]
"git.untrackedDecorator"

**Comment by yuriusu22** [comment]
K. ThX :smile:

**Comment by zheller** [comment]
@yuriusu22 let g:airline#extensions#hunks#coc_git = 1
