### ISSUE TITLE
[Feature Request] Set git gutter diff base

### ISSUE THREAD

**Issue by CallumHoward** [neoclide/coc-git#123]
In `vim-gitgutter` it is [possible](https://github.com/airblade/vim-gitgutter/blob/c27bfab8c51e77419ee0c4a9c4e3ba359dbc2ad4/autoload/gitgutter.vim#L193) to set the diff base for the gutters with something like: 
`:let g:gitgutter_diff_base='master'`.
This is useful on development branches to jump between hunks in a file and see the overall changes before merging a PR.
Could it be considered?

**Comment by CallumHoward** [comment]
Thanks for adding that so quickly! I have tested it and it works great. 
Previously I had some mappings like:
```viml
nnoremap <leader>gg :let g:gitgutter_diff_base='HEAD~'<Left>
nnoremap <leader>ggm :let g:gitgutter_diff_base='master'<CR>
nnoremap <leader>ggh :let g:gitgutter_diff_base=''<CR>
```

So I could change it per vim session without editing config files. Is there a way to set the coc extension config without editing the `coc-settings.json`?

**Comment by chemzqm** [comment]
Use coc#config function or workspace folder configuration

**Comment by CallumHoward** [comment]
Works perfectly, thanks!
```viml
nnoremap <leader>gg :call coc#config('git', {'diffRevision': 'HEAD~'})<Left><Left><Left>
nnoremap <leader>ggm :call coc#config('git', {'diffRevision': 'master'})<CR>
nnoremap <leader>ggh :call coc#config('git', {'diffRevision': 'HEAD'})<CR>
```
