### ISSUE TITLE
vim-coc gets out of sync when I make changes outside of Vim

### ISSUE THREAD

**Issue by oconnor663** [neoclide/coc-git#126]
Here's an example that seems to trigger this:

1. Edit a line in an open text file and save the file. Vim-coc puts the `~` symbol in the signcolumn.
2. Run `git reset --hard` outside of Vim.
3. Execute `:e` inside Vim.

Expected: The `~` should go away (eventually).
Actual: The `~` remains indefinitely.

Am I wrong about the expected behavior here? Is there a way to make vim-coc poll for changes on the filesystem? What's the best way to manually "refresh" it when it gets into this state?

**Comment by chemzqm** [comment]
`:e` should work, please provide vim information.

**Comment by oconnor663** [comment]
I'm sorry, I should've done that at the beginning. This is on Manjaro Linux:

```
NVIM v0.4.3
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/bin/cc -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/build/neovim/src/build/config -I/build/neovim/src/neovim-0.4.3/src -I/usr/include -I/build/neovim/src/build/src/nvim/auto -I/build/neovim/src/build/include
```

My vimrc is visible here: https://github.com/oconnor663/dotfiles/blob/44d325b3066fa77d395da23ed824b2ca0313aef4/vimrc
And my full set of plugins is visible here: https://github.com/oconnor663/dotfiles/blob/44d325b3066fa77d395da23ed824b2ca0313aef4/peru.yaml

The plugins list is:
- vim-airline: https://github.com/vim-airline/vim-airline/commit/768bd0f5c685f728922b98a919cb6fab30c5b4ec
- vim-airline-themes: https://github.com/vim-airline/vim-airline-themes/commit/04fa4fc40f21d9490954213c1ee06c7fdea66a6d
- vim-coc: https://github.com/neoclide/coc.nvim/commit/449dcad0b20080c4f58ae827146fc700287e4141
- vim-commentary: https://github.com/tpope/vim-commentary/commit/f8238d70f873969fb41bf6a6b07ca63a4c0b82b1
- vim-easymotion: https://github.com/easymotion/vim-easymotion/commit/dd7b4b526775bc8553e16bc402020573b04a948c
- vim-fugitive: https://github.com/tpope/vim-fugitive/commit/1da7c133b109cd329060174a104e325e4d6bcc82
- vim-rust: https://github.com/rust-lang/rust.vim/commit/0d8ce07aaa3b95e61bf319b25bb3b1a4ecc780c2
- vim-solarized8: https://github.com/lifepillar/vim-solarized8/commit/5df7666374ead07a482605b53a0f36c27dc17e8d

**Comment by oconnor663** [comment]
A simpler repro for me is:

1. Edit a file in a git repo. Don't save it.
2. Undo the edit with `:e!`.

For me the `~` appears in step 1 (correctly) but remains in step 2 (incorrectly).

**Comment by chemzqm** [comment]
`:e` doesn't reload buffer on neovim 0.4.3, it's recommended to use neovim 0.5.0.
Try add
```
autocmd CursorHold * CocCommand git.refresh
```
to your vimrc.

**Comment by oconnor663** [comment]
Oh my god, `autoread` in NeoVim nightly is amazing. I didn't even know this was a thing :)
