### ISSUE TITLE
git.addGBlameToVirtualText can't work properly with submodules

### ISSUE THREAD

**Issue by ingjieye** [neoclide/coc-git#131]
So I have a project A that has a submodule B which layouts in like A/B.
When in the A project open a file that belongs to B submodule, the blame result that the coc give is always "File not indexed"

<img width="419" alt="image" src="https://user-images.githubusercontent.com/13421169/89135046-f279d680-d55c-11ea-8b4f-9ec72312f35b.png">

**Comment by chemzqm** [comment]
Fixed.
