### ISSUE TITLE
git.stageChunk is not staging

### ISSUE THREAD

**Issue by hassanhafiz44** [neoclide/coc-git#132]
I am inside a chunk, I can see chunkInfo, I can delete chunk using chunkUndo but I am unable to stage using chunkStage

**Comment by 0x8f701** [comment]
@borntokickpk is it the same with mine #133

**Comment by chemzqm** [comment]
Can't reproduce.

**Comment by hassanhafiz44** [comment]
What can't reproduct?

**Comment by chemzqm** [comment]
The file is soft linked?
