### ISSUE TITLE
Question: is there a way to jump to next conflict ? 

### ISSUE THREAD

**Issue by yannham** [neoclide/coc-git#140]
Sorry if that's answered elsewhere, but I couldn't find the answer in the README or in closed issues. Is there a way to map keys to jump to the next or to the previous conflict ?

**Comment by chemzqm** [comment]
No conflict support yet, similar issue #115

**Comment by yannham** [comment]
Would that be difficult to add ? What would be the high-level steps ? I can take a look if I find some time.

**Comment by chemzqm** [comment]
Should be not difficult.

**Comment by yannham** [comment]
I've coded something, but I'm not really familiar with coc extensions. @chemzqm, what is the simplest way to replace the current upstream version of coc-git with my own version locally, so that I can test it ?

**Comment by chemzqm** [comment]
Uninstall it from coc extensions and use `set rtp+=/path/to/coc-git` in your vimrc

**Comment by yannham** [comment]
Thanks, will test and pack it up as a PR once it works
