### ISSUE TITLE
Add support for Bitbucket

### ISSUE THREAD

**Issue by brianfiszman** [neoclide/coc-git#142]
I'm leading a project and actively using coc in neovim as a tool for development.
I love this git coc extension and it would be lovely if I could access the issues from Jira or Bitbucket using this extension.

Regards!

**Comment by chemzqm** [comment]
No, I don't think that related to git, you can create single file coc extension to provide that feature

**Comment by brianfiszman** [comment]
@chemzqm  Maybe I misunderstood but in your documentation, there is support for GitHub and GitLab.
Why not Bitbucket?

**Comment by chemzqm** [comment]
We could support Bitbucket, but not jira

**Comment by brianfiszman** [comment]
> We could support Bitbucket, but not jira
@chemzqm 
Great. I've been using this coc extension lately and I really like it, I'm only asking this feature to take even more advantage out of it. If I changed the title of this feature request issue to "Add Bitbucket as a source for issues", would you reopen it?

**Comment by fannheyward** [comment]
@brianfiszman checkout https://www.npmjs.com/package/coc-jira-complete

**Comment by brianfiszman** [comment]
> @brianfiszman checkout https://www.npmjs.com/package/coc-jira-complete
@fannheyward I do have that extension installed, thanks for mentioning it.
The thing is that even with that extension activated and configured I don't have a list of issues displayed when I write a `:CocList Issues` command. (the extension you mentioned only completes the ticket number when you are creating a commit)
Imho, it would REALLY be awesome and a killer feature to be able to read an issue ticket from there.
![image](https://user-images.githubusercontent.com/13773140/97125585-29eac000-1713-11eb-8a86-27f4406fbe82.png)
