### ISSUE TITLE
How to change BlameVirtualText color 

### ISSUE THREAD

**Issue by vltoo** [neoclide/coc-git#146]
Is there any way we can config the color of the virtual text? 
Would like to make it lighter, it's currently too stand out. Thanks.

<img width="400" alt="image" src="https://user-images.githubusercontent.com/15821031/98962282-57798c80-24bb-11eb-8603-bda2d103264c.png">

**Comment by chemzqm** [comment]
`:h CocCodeLens`

**Comment by darrinholst** [comment]
https://til.hashrocket.com/posts/y6rh9lzhnv-change-the-codelens-annotation-color-in-coc
