### ISSUE TITLE
Fuzzy find conflicts

### ISSUE THREAD

**Issue by AnatoleLucet** [neoclide/coc-git#149]
I'd be nice to have a fuzzy finder for conflicts on the whole repo.

**Comment by chemzqm** [comment]
You can simply grep for `=======`

**Comment by AnatoleLucet** [comment]
Is it possible to display the result in a layout similar to coc-definition ?

![image](https://user-images.githubusercontent.com/35486736/99240583-fcb69c80-27fc-11eb-8723-db0c8e315fc2.png)

**Comment by chemzqm** [comment]
You can implement git conflicts list, PR welcome.
