### ISSUE TITLE
option to disable info of author & date

### ISSUE THREAD

**Issue by 0x8f701** [neoclide/coc-git#150]
![image](https://user-images.githubusercontent.com/33961674/99468777-ac952280-2941-11eb-8181-22534f1738bf.png)

Hi, is it possible to have an option to disable the `(You 5 days ago)` information? I always find it not so useful because most of the time we work on our own code and we don't care that much when I wrote this piece of code.

Normally people will only need this information when there is a problem and when they need to debug, if there is an option people can activate it only when necessary but keep workspace simpler while working.

**Comment by chemzqm** [comment]
PR welcome

**Comment by 0x8f701** [comment]
Close to focus on: https://github.com/neoclide/coc-git/issues/127
