### ISSUE TITLE
Way to revert a chunk?

### ISSUE THREAD

**Issue by djasnowski** [neoclide/coc-git#154]
Let's say I have this via `gs`: 

![image](https://user-images.githubusercontent.com/616320/102037776-39899b00-3d8b-11eb-8af6-d3ef3a8428ed.png)

Is there a way to revert this chunk of code from the green back to red?

**Comment by chemzqm** [comment]
Read readme.

**Comment by djasnowski** [comment]
> Read readme.

I suppose I searched "revert" with no avail. It was UNDOchunk which it was I was needed.

**Comment by chemzqm** [comment]
No if you means staged chunk.
