### ISSUE TITLE
vim-repeat failed with coc-git

### ISSUE THREAD

**Issue by silencial** [neoclide/coc-git#158]
[vim-repeat](https://github.com/tpope/vim-repeat) cannot repeat action with `autocmd CursorHold * :CocCommand git.refresh`

To reproduce, create `mini.vim` as below and run `nvim -u mini.vim [file]`
```vim
set runtimepath^=~/.config/nvim/plugged/coc.nvim
set runtimepath^=~/.config/nvim/plugged/vim-repeat
autocmd CursorHold * :CocCommand git.refresh
```

Press `x` to delete a char, move to another place, wait for 5 seconds, press `.` to repeat, nothing happens.
Not sure whether this is a coc-git problem or vim-repeat problem.

**Comment by chemzqm** [comment]
Don't use that autocmd, your repeat command woukd be overwrite.
