### ISSUE TITLE
Cannot repeat key sequence because of command run by autocommand

### ISSUE THREAD

**Issue by przepompownia** [neoclide/coc-git#159]
Reproduction:
- install vim-repeat and coc-git
- set `autocmd CursorHold,BufWritePost * CocCommand git.refresh`
- do any mapping registered to repeat (except of assigned to git.refresh ;))
- try to repeat the action defined by mapping
- look at `g:repeat_sequence`

I get 
```vim
g:repeat_sequence      <80><fd>S(coc-command-repeat)
```
instead of the action the mapping points to.

**Comment by chemzqm** [comment]
Avoid use CursorHold with CocCommand.

**Comment by przepompownia** [comment]
It may be a step that reduces the amount of unneeded overwritings `g:repeat_sequence`, but the problem still exists and probably it is issue of `CoC`, not only of this extension.
