### ISSUE TITLE
Plug mappings should support the repeat operator

### ISSUE THREAD

**Issue by lewis6991** [neoclide/coc-git#16]
When using the mappings:
```viml
nmap [c <Plug>(coc-git-prevchunk)
nmap ]c <Plug>(coc-git-nextchunk)
```

The `;` operator (motion repeat) does not work. Same goes for `git.hunkStage`.

vim-gitgutter [implements](https://github.com/airblade/vim-gitgutter/blob/8a4b9ccf529db77fa36e5a2308d53783fd70e362/autoload/gitgutter/hunk.vim#L174) repeat by using [vim-repeat](https://github.com/tpope/vim-repeat)

**Comment by chemzqm** [comment]
Fixed by https://github.com/neoclide/coc.nvim/commit/49098ffea5857a465ecc49558da376af89d138c9
