### ISSUE TITLE
Gutters not updating in realtime

### ISSUE THREAD

**Issue by conradob** [neoclide/coc-git#163]
This was working in the past but now after making a commit, the gutter didn't update and the signs keep displaying.

Even when refreshing the buffer with `e!` doesn't update the gutter.

**Comment by chemzqm** [comment]
Could be issue with old vim

**Comment by conradob** [comment]
Sorry, here is the vim version I'm using
```
NVIM v0.5.0-dev+916-gee5ece084
Build type: RelWithDebinfo
LuaJIT 2.1.0-beta3
```

**Comment by timtyrrell** [comment]
I noticed the same. What surprised me is that `:CocRestart` doesn't even clear them. I have no non-default coc-settings configured for `git`

```
:version
NVIM v0.5.0-dev+1062-gcc1851c9f
Build type: Release
LuaJIT 2.1.0-beta3
```

```
- ✓ coc-git Current version 2.2.0 is up to date.
```

```
health#coc#check
========================================================================
  - OK: Environment check passed

  - OK: Javascript bundle build/index.js found
  - OK: Service started
```
