### ISSUE TITLE
Blame Info Not Working

### ISSUE THREAD

**Issue by joshuarubin** [neoclide/coc-git#17]
I've got neovim and coc configured with:
```json
  "git.addGlameToVirtualText": true,
  "git.addGlameToBufferVar": true,
```
However I'm not getting any virtual text nor is `b:coc_git_blame` being set.
Happy to help debug, but don't know where to start.
Thanks!

**Comment by chemzqm** [comment]
Use `:echo exists('*nvim_buf_set_virtual_text')` to check if your neovim support virtual text.

**Comment by joshuarubin** [comment]
`:echo exists('*nvim_buf_set_virtual_text')` returns `1`

**Comment by chemzqm** [comment]
Don't known then, could be something wrong with parse of blame result, you can debug this function https://github.com/neoclide/coc-git/blob/master/src/manager.ts#L81 in chrome https://github.com/neoclide/coc.nvim/wiki/Debug-coc.nvim

**Comment by joshuarubin** [comment]
Looks like this is hitting the next line and returning
```ts
if (!res) return
```

**Comment by joshuarubin** [comment]
Running `git --no-pager blame -b --root -L48,48 --date relative file.go` manually seems fine

**Comment by chemzqm** [comment]
Possible wrong cwd, just made a fix.

**Comment by joshuarubin** [comment]
Ah, I figured it out. nvim is being started from a subdirectory of the git repo so the relative paths it is using are wrong. The error that `safeRun()` is catching (but not logging anywhere), when vim was started in `root/reldir` (but `root/` is the git/project root) is:
```
[coc.nvim] Error on CursorHold: exited with 128
fatal: no such path 'root/reldir/file.go' in HEAD
```
When I start vim from the git/project root, it works fine.

**Comment by chemzqm** [comment]
Try 1.1.6

**Comment by joshuarubin** [comment]
Looks like your fix got it working
