### ISSUE TITLE
Is it possible to show only sign background without text?

### ISSUE THREAD

**Issue by errx** [neoclide/coc-git#173]
Hello. I'am using
`set signcolumn=number`

Is it possible to show only sign background without overriding line number with sign text?

Current behaviour
![image](https://user-images.githubusercontent.com/462486/117691814-fcec8f00-b1c4-11eb-956f-f0ffdf23374e.png)

Desired behaviour
![image](https://user-images.githubusercontent.com/462486/117692626-df6bf500-b1c5-11eb-9dc5-ea089686cc12.png)

**Comment by chemzqm** [comment]
No, it's not possible with current vim or neovim.
