### ISSUE TITLE
sometimes gitchunkstage doesn't work well on the last line

### ISSUE THREAD

**Issue by 0x8f701** [neoclide/coc-git#175]
<img width="730" alt="image" src="https://user-images.githubusercontent.com/33961674/118739279-a5f95080-b87b-11eb-885c-f49c75535e21.png">

gitchunkstage always work on other lines, but sometimes it doesn't work on the last line, I can reproduce this in json file

**Comment by chemzqm** [comment]
Can't reproduce., `GitChunkStage` is not from coc-git
