### ISSUE TITLE
Non-blocking Git push

### ISSUE THREAD

**Issue by Maswor** [neoclide/coc-git#180]
Hi

First of all, thank you for the plugin. I use coc-git everyday instead of using git directly in the terminal.

One issues I have with it though, is it depend on vim-fugitive for commits and push. I have a repo behind a VPN, and if I forgot to turn the VPN on, **vim-fugitive** just hang the whole Neovim program.

**Gina.nvim** however, doesn't suffer from this issues. It would be great if I can configure **coc-git** to use Gina.nvim for push. If coc-git can come up with a built in solution, it would even be better.

Thank you and best regards

**Comment by chemzqm** [comment]
It doesn't use other vim plugin for `git push`, checkout https://github.com/neoclide/coc-git/blob/master/src/manager.ts#L257
