### ISSUE TITLE
Git gutter highlight doesn't work with signcolumn=number

### ISSUE THREAD

**Issue by ravisumit33** [neoclide/coc-git#181]
I was using `signcolumn = yes` and had highlight of git gutters working properly as below:

<img width="914" alt="Screenshot 2021-06-18 at 3 45 21 PM" src="https://user-images.githubusercontent.com/19284116/122546064-329a5880-d04c-11eb-9863-d16aebf57ae1.png">

When I switched to `signcolumn=number` git gutters highlights stopped working and they become white.

<img width="953" alt="Screenshot 2021-06-18 at 3 46 28 PM" src="https://user-images.githubusercontent.com/19284116/122546214-5a89bc00-d04c-11eb-9d98-ba936031bbcd.png">

Any idea why is this happening? Am I missing any configuration?

**Comment by chemzqm** [comment]
Upgrade your coc-git

**Comment by chemzqm** [comment]
Upgrade your coc-git

**Comment by chemzqm** [comment]
Upgrade your coc-git

**Comment by ravisumit33** [comment]
@chemzqm coc-git is latest version `2.3.5`

<img width="610" alt="Screenshot 2021-06-18 at 6 05 54 PM" src="https://user-images.githubusercontent.com/19284116/122561724-d4777080-d05f-11eb-8b84-ff7f1221cf9e.png">

**Comment by chemzqm** [comment]
I see your image now, it's working as expected since we can't change background for that case, it's vim's issue.

**Comment by ravisumit33** [comment]
@chemzqm  I think its not vim's issue. If I use [vim-gitgutter](https://github.com/airblade/vim-gitgutter), gutters are colored. As you can see below change gutter is green.

<img width="857" alt="Screenshot 2021-06-18 at 6 21 33 PM" src="https://user-images.githubusercontent.com/19284116/122563630-0d184980-d062-11eb-97e7-07c60c1f5d4b.png">

**Comment by ravisumit33** [comment]
I tried using git gutter symbols in coc-git as suggested in readme but they still doesn't have color.

**Comment by ravisumit33** [comment]
Also, diagnostics are working fine. Only coc-git gutters are plain white.

**Comment by ravisumit33** [comment]
@chemzqm I think gutters from coc-git should also be colored

**Comment by ravisumit33** [comment]
> I see your image now, it's working as expected since we can't change background for that case, it's vim's issue.

@chemzqm  You are right. Its neovim's issue. Its working fine on vim

<img width="924" alt="Screenshot 2021-06-19 at 2 06 07 PM" src="https://user-images.githubusercontent.com/19284116/122636552-8027cb80-d107-11eb-9825-c1afbd561f3d.png">
