### ISSUE TITLE
Issue completion only works when trigggered automatically

### ISSUE THREAD

**Issue by eliasnorrby** [neoclide/coc-git#185]
The [`doComplete`](https://github.com/neoclide/coc-git/blob/7d91f4bdf3550ccd294f5d5a2072d5dd71678b0f/src/source.ts#L229) function has a check for `triggerCharacter == '#'`, which makes sense: we only want to suggest issues when this prefix is used. 

I have `coc-nvim` set up so that I have to trigger completion manually, i.e.

```json
"suggest.autoTrigger": "none"
```

and completion is triggered with `tab` or `ctrl + space`. 

When completion is invoked manully, `opt.triggerCharacter` is `undefined`, so no issues will be suggested.

**Comment by chemzqm** [comment]
Fixed by 6b03d319
