### ISSUE TITLE
Highlight for diff content disappears when using `:CocCommand git.showCommit`

### ISSUE THREAD

**Issue by voldikss** [neoclide/coc-git#186]
As shown in the gif,

- `:CocCommand git.showCommit` opens a floating window with diff content
- `:wincmd p` jumps to that window, highlight exists.
- `G` jumps to the end of the buffer, **the highlight is gone**
- `gg` jumps to the first line, the highlight goes back.

![coc-git gif](https://user-images.githubusercontent.com/20282795/125481489-978e5cdf-81ee-40f9-9eb5-12db35ce6d53.gif)

Seems that the implementation [here](https://github.com/neoclide/coc.nvim/blob/acc2b95be6652d79f86d586e52c7566557608476/autoload/coc/highlight.vim#L311) is not good for the highlight for huge amount of lines. 

Please help :pray:

**Comment by chemzqm** [comment]
That commit is only 150 lines and the highlights works fine for me.
Use ` "git.showCommitInFloating": false` in your coc-settings.json.
