### ISSUE TITLE
Signs are not highlighted with `signcolumn=number`

### ISSUE THREAD

**Issue by gdzx** [neoclide/coc-git#187]
Hi!

With:

- NVIM v0.5.0
- Node v16.4.2
- coc.nvim 0.0.80-9fd90ad761
- coc-git 2.4.3

And `signcolumn=number`, the diagnostic signs are highlighted properly, but the git signs are not:

![signs](https://user-images.githubusercontent.com/6490707/127394150-cdd8e31d-cb0e-4d63-b13b-2a88d9452c9c.png)

Excerpt of the sign list:

```vim
sign CocError text=E> linehl=CocErrorLine texthl=CocErrorSign
sign CocGitAdded text=+  numhl=CocGitAddedSign
```

It seems that `coc.vim` [adds `texthl` regardless of `signcolumn`](https://github.com/neoclide/coc.nvim/blob/5aa3197360a76200e8beb30c9957fac1205b7ad5/src/diagnostic/manager.ts#L118):

```vim
let signText = this.config[kind.toLowerCase() + 'Sign']
let cmd = `sign define Coc${kind} linehl=Coc${kind}Line`
if (signText) cmd += ` texthl=Coc${kind}Sign text=${signText}`
if (enableHighlightLineNumber) cmd += ` numhl=Coc${kind}Sign`
```

Whereas `coc-git` [replaces `texthl` by `numhl` if `signcolumn=number`](https://github.com/neoclide/coc-git/blob/48dc6cda3c2537069f0f196139fb4223fe5d2e8d/src/manager.ts#L83):

```vim
let numhl = signcolumn == 'number' && workspace.isNvim && semver.gte(workspace.env.version, 'v0.3.2')
"...
let extra = numhl ? `numhl=CocGit${item}Sign` : `texthl=CocGit${item}Sign`
nvim.command(`sign define CocGit${item} text=${text} ${extra}`, true)
```

Maybe the `enableHighlightLineNumber` configuration setting could be used as well in `coc-git`?

Best regards.

**Comment by gdzx** [comment]
Related: #181

**Comment by chemzqm** [comment]
Yes, PR welcome
