### ISSUE TITLE
Unhandled Rejection: import_coc11.workspace.has is not a function

### ISSUE THREAD

**Issue by ic-768** [neoclide/coc-git#192]
I have installed using `:CocInstall coc-git`, and added the `addGBlameToVirtualText` flag to my coc-settings.json, but it doesn't work.

![screenshot](https://user-images.githubusercontent.com/83115125/151212396-07444a5c-bfa5-4ed8-8610-78ac5b396548.png)

**Comment by chemzqm** [comment]
Please upgrade your coc.nvim.
