### ISSUE TITLE
`gstatus` with auto-preview failed if there is a new ADD file

### ISSUE THREAD

**Issue by fannheyward** [neoclide/coc-git#2]
1. `CocList --auto-preview --normal gstatus`
2. git status lists in coc-list, for example:
```
~ A
~ B
+ C
```
3. auto-preview shows diff of A, It's OK
4. `j` move to B, auto-preview is OK
5. `j` again to C, auto-preview is broken.
6. `k` to B, auto-preview is still broken.

Thanks for your work, COC becomes more and more great, again and again :D

**Comment by chemzqm** [comment]
It's expected, maybe change later.
