### ISSUE TITLE
Enabling the gutter signs slows down Vim movement keys

### ISSUE THREAD

**Issue by asgeo1** [neoclide/coc-git#20]
This plugin appears to be redrawing the gutter signs constantly, pretty much after any key-press.

Personally, I find that a pain as it slows down the movement keys in Vim. I am noticing a real lag when moving around a file, or even when typing in insert-mode

I'm a user coming from vim-gitgutter. In that plugin, I had the same issue too. But luckily that plugin had some settings you could turn off, effectively making it so signs are only updated when the buffer is written:

```
let g:gitgutter_eager = 0
let g:gitgutter_realtime = 0
```

That way typing-performance is not impacted at all.

I can't see any such settings for this plugin.  If there isn't any, can such settings be added?

**Comment by chemzqm** [comment]
No such option,might be added in future, you can disable gutters of coc-git and use vim-gitgutter.
