### ISSUE TITLE
Comparison to fugitive

### ISSUE THREAD

**Issue by HaleTom** [neoclide/coc-git#28]
Thanks for the great work on CoC!

I'm trying to work whether to switch from `fugitive`.

Could you please point out the similarities and differences between this plugin and [`vim-fugitive`](https://github.com/tpope/vim-fugitive)?

**Comment by chemzqm** [comment]
You should not, it doesn't provide most features that fugitive has.  Is use fugitive command when possible for things like gitcommit.
