### ISSUE TITLE
Refresh when refocussing window after CLI `git commit`

### ISSUE THREAD

**Issue by tombh** [neoclide/coc-git#32]
I'm still in the habit of commit on the command line in a separate pane, so when I come back to vim after committing the gutters are still there which often confuses as I mistakenly think that I left that file out of my `git add`. Is it possible to have another hook to update the gutters for this case?

**Comment by chemzqm** [comment]
Seems you're using old version of coc-git.

**Comment by tombh** [comment]
My `~/.config/coc/extensions/node_modules/coc-git/package.json` says 1.5.3, so I think that's the latest? Is there any debug info I could send you?

**Comment by chemzqm** [comment]
It's refreshed on CursorHold, consider use `let udpatetime=300` in your vimrc.

**Comment by tombh** [comment]
I dug through this a bit. I realise now that it's because I'm so often in Insert Mode, I know it's bad, but I very rarely use Normal Mode. So what I need is _Insert Mde's_ `CursorHoldI` event, something like:

`autocmd CursorHoldI * call s:Autocmd('CursorHold', +expand('<abuf>'))`

But of course that doesn't work because it is a script local function (`s:`).

I also notice that even when I am in Normal Mode, `BufEnter` still doesn't trigger a refresh as Normal Mode's `CursorHold` is only triggered after the cursor has been moved and then held in position for `updatetime` milliseconds.

**Comment by tombh** [comment]
Thanks for the `BufEnter` commit.
