### ISSUE TITLE
Gitlab support

### ISSUE THREAD

**Issue by Herz3h** [neoclide/coc-git#39]
Does it allow to complete from gitlab issues ?

**Comment by chemzqm** [comment]
No, I don't know the API used by gitlab.

**Comment by Herz3h** [comment]
Ok thank you.

**Comment by fannheyward** [comment]
I've added GitLab issue support in PR https://github.com/neoclide/coc-git/pull/48.

The difficult of GitLab support is that, GitLab provides two version API, v3 & v4, and `gitlab.com` supports v4 only, so I just support v4.

@chemzqm these changes will not broken GitHub support, so maybe we can release a new version `coc-git` to get more user feedbacks.
