### ISSUE TITLE
Running chunkStage with repeat is completely broken

### ISSUE THREAD

**Issue by lewis6991** [neoclide/coc-git#45]
I currently have this mapping: 
```
nmap <leader>hs :CocCommand git.chunkStage<cr>
```

And I will run through a file and run `<leader>hs` to begin staging chunks and repeat with `.` for all subsequent chunks I want to stage.

However doing this for even basic cases seems to be completely broken and coc seems to perform random edits in the buffer when performing `.`

**Comment by chemzqm** [comment]
~You should use keymappings that provided~

**Comment by lewis6991** [comment]
> You should use keymappings that provided

This plugin only provides `<Plug>` mappings and doesn't provide one `chunkStage`. Regardless, coc-nvim has support for [vim-repeat](https://github.com/tpope/vim-repeat) and using the `.` is very [idiomatic](http://vimcasts.org/episodes/modal-editing-undo-redo-and-repeat/) vim

**Comment by chemzqm** [comment]
Fixed on latest coc.nvim.
