### ISSUE TITLE
Diff against remote rather than local

### ISSUE THREAD

**Issue by noboruma** [neoclide/coc-git#47]
Hello there,

Is it possible to see the diff (diff symbols inside the documents) against origin rather than against the latest local commit?
Sometimes I would like to see what I changed relatively to the remote branch, would be nice to have a toggling option for that?

**Comment by chemzqm** [comment]
You have to use other tools, like `:Gdiffsplit` provided by vim-fugitive.

**Comment by noboruma** [comment]
The problem with `vim-fugitive` is that this is intrusive.
What I really want to do is, dev on a branch & commit changes to that branch. But I still want to see the lines I modified up until I actually push my branch changes.
Would it be possible to have different colors (in the left column), depending on whether the changes are ahead of HEAD or uncommitted changes (current behavior)?
I still think this would be a very useful feature to have, but this is up to you :)

**Comment by chemzqm** [comment]
You can use https://github.com/mhinz/vim-signify for those diff signs.
I don't want to support multiple signcolumns.
