### ISSUE TITLE
Background color doesn't match

### ISSUE THREAD

**Issue by itainoam** [neoclide/coc-git#69]
The gutter changes are displayed in a different background color (as opposed to other signs in the gutter such as eslint or typescript errors):

![image](https://user-images.githubusercontent.com/12605830/67266750-9e17d580-f4b9-11e9-9c6a-882fe1b0e318.png)

Any idea what might causing it? That's my coc-settings.json:
```
{
   "coc.preferences.formatOnSaveFiletypes":[  
      "css",
      "Markdown",
      "javascript",
      "javascriptreact",
      "typescript",
      "json"
   ],
   "javascript.suggest.enabled":false,
   "suggest.autoTrigger":"none",
}

```

**Comment by chemzqm** [comment]
The problem is your error sign have it's own background color.
Read https://github.com/neoclide/coc-git/blob/master/Readme.md#configuration for highlight groups coc-git used for gutter.
