### ISSUE TITLE
Incorrect signs shown on Windows 10 + Neovim

### ISSUE THREAD

**Issue by ghost** [neoclide/coc-git#73]
On a git [repository ](https://github.com/cf91/.dotfiles) in Windows 10, I ensure the working tree is clean (`git status`). If I open up a [small file](https://github.com/cf91/.dotfiles/blob/master/README.md) in the repo no signs are shown (correct) and the changes I make are reflected in the signs correctly. If I open my [coc-settings.json](https://github.com/cf91/.dotfiles/blob/master/nvim/coc-settings.json) (a larger file in the same repository) the signs are meaningless.

See the below screenshot, this is on a clean working tree with no changes:
![image](https://user-images.githubusercontent.com/56765055/68697693-5e3e8e00-054d-11ea-960c-03c35360f788.png)

Please let me know how I can help you debug this, any logging I can share? Thanks.

**Comment by chemzqm** [comment]
https://github.com/neoclide/coc.nvim/wiki/Debug-language-server#using-output-channel
Please provide verbose output.

**Comment by ghost** [comment]
This is the most I could get:

```
## versions

vim version: NVIM v0.4.2
node version: v10.15.3
coc.nvim version: 0.0.74-377c2729b9
term: undefined
platform: win32

## Messages


## Output channel: snippets


## Output channel: prettier


## Output channel: git

Looking for git in: git
> git rev-parse --show-toplevel
resolved root: c:\Users\xxx\.dotfiles
> git ls-files -- README.md
> git --no-pager show :README.md
resolved root: c:\Users\xxx\.dotfiles
> git ls-files -- README.md
> git --no-pager show :README.md
resolved root: c:\Users\xxx\.dotfiles
> git ls-files -- README.md
resolved root: c:\Users\xxx\.dotfiles
> git ls-files -- nvim\ginit.vim
> git --no-pager show :README.md
> git --no-pager show :nvim\ginit.vim
resolved root: c:\Users\xxx\.dotfiles
> git ls-files -- nvim\init.vim
> git --no-pager show :nvim\init.vim
> git diff c:\Users\xxx\.dotfiles\nvim\init.vim
resolved root: c:\Users\xxx\.dotfiles
> git ls-files -- nvim\init.vim
> git --no-pager show :nvim\init.vim
> git diff c:\Users\xxx\.dotfiles\nvim\init.vim
resolved root: c:\Users\xxx\.dotfiles
> git ls-files -- nvim\init.vim
> git --no-pager show :nvim\init.vim
> git diff c:\Users\xxx\.dotfiles\nvim\init.vim
resolved root: c:\Users\xxx\.dotfiles
> git ls-files -- nvim\init.vim
> git --no-pager show :nvim\init.vim
> git diff c:\Users\xxx\.dotfiles\nvim\init.vim
resolved root: c:\Users\xxx\.dotfiles
> git ls-files -- nvim\init.vim
> git --no-pager show :nvim\init.vim

## Output channel: markdownlint

[10:44:12 AM] Info: global config: {"_":[]}
[10:44:12 AM] Info: config from coc-settings.json: {}
[10:44:12 AM] Info: full config: {"_":[]}

## Output channel: highlight

[Info  - 10:44:13 AM] Highlight server running in node v10.15.3
```

It's me switching between 3 files. README.md shows correct signs and updates, ginit.vim also is correct (both small files), init.vim is 508 lines and has no changes and shows signs totally off as in the above screenshot.

**Comment by chemzqm** [comment]
```
- `git.realtimeGutters`: Change to `false` when you want gutters update only on save, default: `true`.
```
You have disabled realtime gutters.

**Comment by chemzqm** [comment]
Try minimal vimrc, I can't reproduce.

**Comment by ghost** [comment]
It's okay, seems it's a strange/difficult issue to debug, probably related to Windows+git combo. Keep up the awesome work.

**Comment by chemzqm** [comment]
Looks like BufNewFile event not triggered with file coc-settings.json
