### ISSUE TITLE
Git chunk not shows up in diff window. 

### ISSUE THREAD

**Issue by lkhphuc** [neoclide/coc-git#77]
Hi, 
when I display the diff of my file using vim-fugitive, the window on the left (the previous commit) does not display git chunk, only the window on the right (the working area) display git chunk.

Therefore I can not navigate around with shortcut with chunk in the default left window.
<img width="1101" alt="Screenshot 2019-12-27 at 17 59 26" src="https://user-images.githubusercontent.com/12573521/71527284-a124ad00-28d2-11ea-91c3-1c4c979f5aa4.png">

Previous I use Signify and the navigation with chunks works fine on both windows.
I don't know if this is a bug or is there any config that enable git chunk on both of them?

Thank you for your work.

**Comment by chemzqm** [comment]
No idea what do you mean, if it's diff provided by  vim-fugitive, you need ask question there.

**Comment by lkhphuc** [comment]
For future reference, I solve my issue using `[c` described in https://github.com/neoclide/coc.nvim/issues/1119
