### ISSUE TITLE
[coc.nvim] error: UnhandledRejection: TypeError: Cannot read property 'bufnr' of null #1278

### ISSUE THREAD

**Issue by oblitum** [neoclide/coc-git#78]
Moving https://github.com/neoclide/coc.nvim/issues/1278 here because I can only reproduce it with coc-git.

Temporary fix is to patch coc-git release with:

```diff
--- lib/index.js.orig   2020-01-22 00:01:08.806144997 -0300
+++ lib/index.js        2020-01-21 17:58:31.012656259 -0300
@@ -4459,6 +4459,7 @@
     }
     diffDocument(doc, init = false) {
         return __awaiter(this, void 0, void 0, function* () {
+            if (doc == null) return;
             let { nvim } = coc_nvim_1.workspace;
             let repo = yield this.getRepo(doc.bufnr);
             if (!repo)
```

Which corresponds to change this part of the code:

https://github.com/neoclide/coc-git/blob/6335354b9a1df79be5a3a87188a9ffde2857de01/src/manager.ts#L402

Please check original issue for additional logs and other user reports.

**Comment by oblitum** [comment]
@chemzqm f807edc did not fix the issue, still have to use my patch.

**Comment by oblitum** [comment]
Please notice bug and "fix" is confirmed by other users: https://github.com/neoclide/coc.nvim/issues/1278#issuecomment-574254269.

**Comment by oblitum** [comment]
Maybe `doc` argument needs to be checked in other places it's being passed to `diffDocument`.

**Comment by oblitum** [comment]
Can this be reopened as it's still present and I have to apply to patch to avoid it?

**Comment by voldikss** [comment]
Hi @chemzqm , I can confirm this issue still exists. Cloud we reopen the issue and fix it?

**Comment by voldikss** [comment]
Tested on my laptop, this patch can fix the issue.
```diff
diff --git a/src/index.ts b/src/index.ts
index 680022b..794d9ee 100644
--- a/src/index.ts
+++ b/src/index.ts
@@ -55,6 +55,7 @@ export async function activate(context: ExtensionContext): Promise<void> {

   workspace.onDidChangeTextDocument(async e => {
     let doc = workspace.getDocument(e.textDocument.uri)
+    if (!doc) return
     await manager.diffDocument(doc)
   }, null, subscriptions)
```
Could we patch it?

**Comment by oblitum** [comment]
31150e5afc728f269234bee45825e2cc50eeac6e
