### ISSUE TITLE
specify background color for git gutter

### ISSUE THREAD

**Issue by francois-pasquier** [neoclide/coc-git#79]
Is it possible to specify the background color for git gutter or to simply not have one?

**Comment by chemzqm** [comment]
Check doc of vim, should be SignColumn

**Comment by francois-pasquier** [comment]
This plugin has this config:
```json
{
"git.addedSign.hlGroup": {
          "type": "string",
          "default": "DiffAdd",
          "description": "Highlight group for added sign."
        }
}
```

The problem is that setting this doesn't work as intended:

```vim
hi! DiffAdd ctermbg=darkred ctermfg=blue guibg=darkred guifg=blue
```

The bg values control the fg color of the DiffAdd group and fg values control the bg color.

Settings guifg=NONE renders a white color and doesn't render a transparent one.

Can this be fixed?

**Comment by chemzqm** [comment]
Try `:hi DiffAdd`

**Comment by francois-pasquier** [comment]
Well, as I said, `:hi  DiffAdd` does change the color (it's reverted for some reason) but I can't set it to None. It doesn't respect this value

**Comment by chemzqm** [comment]
Can't reproduce

**Comment by Andoku** [comment]
I have the same problem, my colors are inverted somehow.
<img width="43" alt="Снимок экрана 2021-01-30 в 20 37 03" src="https://user-images.githubusercontent.com/669031/106363661-f1263c80-633a-11eb-8a35-e53d22dcf326.png">
<img width="50" alt="Снимок экрана 2021-01-30 в 20 37 41" src="https://user-images.githubusercontent.com/669031/106363681-131fbf00-633b-11eb-9dad-2e24c1ec795a.png">
<img width="52" alt="Снимок экрана 2021-01-30 в 20 38 05" src="https://user-images.githubusercontent.com/669031/106363682-15821900-633b-11eb-83c7-2ac23bcd396a.png">
