### ISSUE TITLE
Error on active extension coc-git: TypeError: coc_nvim_1.FloatFactory is not a constructor

### ISSUE THREAD

**Issue by giovannigiordano** [neoclide/coc-git#8]
I am trying to install `coc-git` but I have the following error
`Error on active extension coc-git: TypeError: coc_nvim_1.FloatFactory is not a constructor`

### Ouput of CocInfo:
```
## versions

vim version: NVIM v0.4.0-dev
node version: v10.15.1
coc.nvim version: 0.0.65-5effa64974
term: Apple_Terminal
platform: darwin

```

**Comment by chemzqm** [comment]
Use `:call coc#util#install()` to install latest build.

**Comment by edgard** [comment]
Same here, I'm trying to install as every other coc plugin with npm install from vim-plug.
