### ISSUE TITLE
Disable vim folds on floating chunk info

### ISSUE THREAD

**Issue by comfortablynick** [neoclide/coc-git#81]
The chunk info floating win opens with closed folds in some cases.

I have been able to get around this by adding this autocmd, but it seems like a sensible default to me:

```vim
autocmd User CocOpenFloat if exists('w:float') | setl nofloatenable | endif
```
Here is what it looks like without the autocmd:
![coc-git-float](https://i.imgur.com/l2RdQKO.jpg)

Gitgutter displays it properly so I don't think it's a global configuration issue.

**Comment by chemzqm** [comment]
Please provide result from `:CocInfo`

**Comment by comfortablynick** [comment]
## versions                                                                                                                                                                                        
                                                                                                                                                                                                     
  vim version: NVIM v0.5.0-350-g14a8b3b98                                                                                                                                                            
  node version: v10.16.3                                                                                                                                                                             
  coc.nvim version: 0.0.74                                                                                                                                                                           
  term: screen-256color                                                                                                                                                                              
  platform: linux                                                                                                                                                                                    
                                                                                                                                                                                                     
  ## Messages                                                                                                                                                                                        
                                                                                                                                                                                                     
  ## Output channel: snippets                                                                                                                                                                        
                                                                                                                                                                                                     
                                                                                                                                                                                                     
  ## Output channel: explorer                                                                                                                                                                        
                                                                                                                                                                                                     
                                                                                                                                                                                                     
  ## Output channel: git                                                                                                                                                                             
                                                                                                                                                                                                     
  Looking for git in: git                                                                                                                                                                            
  > git rev-parse --show-toplevel                                                                                                                                                                    
  resolved root: /home/nick/dotfiles                                                                                                                                                                 
  > git ls-files -- dotfiles/.vim/plugin/editor.vim                                                                                                                                                  
  resolved root: /home/nick/dotfiles                                                                                                                                                                 
  > git symbolic-ref --short HEAD                                                                                                                                                                    
  > git diff --name-status                                                                                                                                                                           
  > git diff --staged --name-status                                                                                                                                                                  
  > git ls-files --others --exclude-standard                                                                                                                                                         
  > git --no-pager show :dotfiles/.vim/plugin/editor.vim                                                                                                                                             
  resolved root: /home/nick/dotfiles                                                                                                                                                                 
  resolved root: /home/nick/dotfiles                                                                                                                                                                 
  > git symbolic-ref --short HEAD                                                                                                                                                                    
  > git ls-files -- dotfiles/.vim/plugin/editor.vim                                                                                                                                                  
  > git diff --name-status                                                                                                                                                                           
  > git diff --staged --name-status                                                                                                                                                                  
  > git ls-files --others --exclude-standard                                                                                                                                                         
  > git --no-pager show :dotfiles/.vim/plugin/editor.vim

**Comment by chemzqm** [comment]
Can't reproduce, looks like some plugin add fold to that buffer.
Try add `autocmd User CocOpenFloat setl nofen` to your vimrc.
