### ISSUE TITLE
New feature request: redoChunk

### ISSUE THREAD

**Issue by mrassili** [neoclide/coc-git#90]
Hi

I see that sometimes, you undo a chunk and figure you want `redo` it,
I know `u` can do it but when you have made other changes in the file, it gets messy

I suggest we implement a new command `redoChunk`.
Not sure what was the reasoning behind omitting this command from the start?

**Comment by chemzqm** [comment]
No, it's not necessary, we can break undo history before undo trunk.

**Comment by mrassili** [comment]
@chemzqm I didn't get it, what did you mean by `break undo history before undo trunk` care to explain, please?

**Comment by chemzqm** [comment]
Use plugin like https://github.com/simnalamburt/vim-mundo to manage your undo history, we will not support redo chunk.
