### ISSUE TITLE
modified sign is clobbering signs

### ISSUE THREAD

**Issue by aganm** [neoclide/coc-git#92]
The addition sign (green +) and substration sign (red -) don't clobber my linting signs, but the modified sign (gray ~) does.

**Comment by chemzqm** [comment]
Can't understand.

**Comment by aganm** [comment]
I have signs in my gutter from my linter that shows me where warnings and errors are. And I have signs from git gutter that shows changes (+,-). When I have a warning and a change on the same line, the git gutter sign hides the warning. I want the linter sign to have priority.

**Comment by chemzqm** [comment]
Please read https://github.com/neoclide/coc-git#configuration

**Comment by aganm** [comment]
Is this the config I have to change? 
`oc.source.issues.priority`
I set it to 0, and I set to to 99, same result,
The gitgutter sign has priority over the linter.
Someone can help?
