### ISSUE TITLE
chunkUndo stopped working

### ISSUE THREAD

**Issue by oblitum** [neoclide/coc-git#93]
Recently `:CocCommand git.chunkUndo` isn't working correctly:

![screencast](https://user-images.githubusercontent.com/1269815/76354659-a5693f80-62f1-11ea-82ae-9cece05f1067.gif)

In this gif, the first chunkUndo reverts in two places, the second attempt duplicates text.

**Comment by frescoraja** [comment]
seems like its from this commit:
https://github.com/neoclide/coc-git/commit/21459fe2d7785008c9f2913f8344fc4039c4338c
removing the line added in that commit restores functionality as it was before
