### ISSUE TITLE
Example of how to update status line properly

### ISSUE THREAD

**Issue by alex-popov-tech** [neoclide/coc-git#94]
Hello! thanks for a great extension!
Is there some example on how to update status line to see current git status?
I tried this:
```
autocmd User CocGitStatusChange call s:update_status()
function! s:update_status()
  let g:airline_section_b = b:coc_git_status
endfunction
```
but this does not work ( only once, when loading vimrc )

PS: `g:coc_git_status` shows me `master ...` - is there a way to see added/deleted/modified lines for whole project?

**Comment by alex-popov-tech** [comment]
actually, it seems to have some problems on my side as well...so here is my airline config now - https://github.com/alex-popov-tech/.dotfiles/blob/master/nvim/plugins/airline.vim#L5

It does not shows `coc-git-status` by default, so how can i enable that?

**Comment by chemzqm** [comment]
Checkout doc of airline of how to add buffer variable to your status line.

> is there a way to see added/deleted/modified lines for whole project?

No such support.
