### ISSUE TITLE
How to check, if coc-git is installed

### ISSUE THREAD

**Issue by chrisbra** [neoclide/coc-git#96]
Hi,
how do I check from another plugin, whether coc-git is available? This is needed for better vim-airline integration. Thanks.

**Comment by chemzqm** [comment]
Try `:echo CocAction('extensionStats')`

**Comment by chrisbra** [comment]
> Try :echo CocAction('extensionStats')

I want to check it from another plugin, not interactively. So if I want to check it from another plugin, how do I do it? Is there a public available variable, that I can check? Or a function that is available?

**Comment by chemzqm** [comment]
`CocAction('extensionStats')` returns a list of extensions, you can check if there is a item with `id` as `coc-git`

**Comment by chrisbra** [comment]
So that is a function?

**Comment by chemzqm** [comment]
Sure

**Comment by chrisbra** [comment]
Hm, this doesn't output anything, `:echo CocAction('extensionStats')`, however `:let g:a=CocAction('extensionStats')` does show something.

```
:echo CocAction('extensionStats')
:echo g:coc_git_status
 master…
:echo b:coc_git_status
E121: undefined variable
```

What am I doing wrong? This is in a dirty file in the current git directory.

**Comment by chemzqm** [comment]
No idea, it should return a list of extension stat.

**Comment by chrisbra** [comment]
Anyhow, I integrated it into the hunk extension of vim-airline.
