### ISSUE TITLE
[coc.nvim] Error on "CocList commits": Error: exited with ERR_CHILD_PROCESS_STDIO_MAXBUFFER 

### ISSUE THREAD

**Issue by jacobaclarke** [neoclide/coc-git#97]
When trying to do a diffsplit on a with a commit 2 or 3 commits back in the commit history, I git this error.

To reproduce,

:Coclist commits
Go a couple commits down
Hit <tab>
Hit D

**Comment by chemzqm** [comment]
Fixed.
