### ISSUE TITLE
oc.source.issues.priority  does nothing

### ISSUE THREAD

**Issue by aganm** [neoclide/coc-git#99]
I have this problem that coc-git is clobbering my signs.
I looked at the configuration but found nothing regarding that except for this value
`oc.source.issues.priority`
I set it to 0, and I set to to 99, same result,
The gitgutter sign has priority over the linter (ALE).
I want to see the linter signs, can someone help with that?
You can see '~' character from coc-git on the left, where there's also a '>>' from the linter.
![GIF](https://user-images.githubusercontent.com/20380758/78422604-7616cb80-762e-11ea-939f-71d686604842.gif)

**Comment by chemzqm** [comment]
It's priority of completion source use diagnostic.signOffset instead
